### ISSUE TITLE
Netdata installer

### ISSUE THREAD

**Issue by wirwolf** [sysadmws/sysadmws-formula#26]
В дебиане не могу поставить нетдату из-за ошибки в установке зависимостей.

```
----------
          ID: netdata_depencies_installed
    Function: pkg.installed
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit: run-rfd76c39e3bf34d579abe4dfbf4a677c7.scope
                    E: Sub-process /usr/share/proxmox-ve/pve-apt-hook returned an error code (1)
                    E: Failure running script /usr/share/proxmox-ve/pve-apt-hook
     Started: 15:13:50.070576
    Duration: 2303.033 ms
     Changes:   

```
Переписать код установки на 
```
https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh
```

```
./install-required-packages.sh --dont-wait --non-interactive netdata-all
```

система проверяет ось и в зависимости от этого ставит нужные пакеты
